import { Apartment } from '../apartment-listing/apartment';

export const apartmentData: Apartment[] = [
  {
    id: 1,
    name: 'Cozy Studio',
    title: 'A Bright Studio in the Heart of Downtown',
    type: 'Apartment',
    image: 'images/apartment-1.jpg',
    rent: 1200,
    location: 'Downtown',
    isShared: false,
    areaInSqFeet: '520 sq ft',
    isFurnished: true,
    amenities: ['Elevator', 'Laundry Service', 'Gated Security'],
    stayType: 'l',
    isNegotiable: false,
    description:
      'A small but comfortable studio apartment in the heart of the city. Perfect for singles or couples looking for a convenient location.',
    owner: 'john.doe@example.com',
  },
  {
    id: 2,
    name: 'Spacious 2-Bedroom',
    title: 'Spacious Family Home Near the Suburbs',
    type: 'Building',
    image: 'images/apartment-2.jpg',
    rent: 2000,
    location: 'Suburbs',
    isShared: true,
    areaInSqFeet: '1,120 sq ft',
    isFurnished: false,
    amenities: ['Car Parking', 'Visitor Parking', 'Private Lawn'],
    stayType: 'ls',
    isNegotiable: true,
    description:
      'A large two-bedroom apartment with a great view and modern amenities. Ideal for families or roommates seeking extra space and comfort.',
    owner: 'john.doe@example.com',
  },
  {
    id: 3,
    name: 'Luxury Penthouse',
    title: 'Luxury Skyline Penthouse with Premium Finishes',
    type: 'Building',
    image: 'images/apartment-3.jpg',
    rent: 5000,
    location: 'Uptown',
    isShared: false,
    areaInSqFeet: '2,400 sq ft',
    isFurnished: true,
    amenities: ['Swimming Pool', 'Gym', 'Elevator', 'Gated Security'],
    stayType: 'l',
    isNegotiable: true,
    description:
      'A luxurious penthouse with stunning city views and top-of-the-line features. Perfect for those who want to live in style and enjoy the finer things in life.',
    owner: 'john.doe@example.com',
  },
  {
    id: 4,
    name: 'Charming 1-Bedroom',
    title: 'Charming One-Bedroom with Modern Comforts',
    type: 'Apartment',
    image: 'images/apartment-4.jpg',
    rent: 1500,
    location: 'Midtown',
    isShared: false,
    areaInSqFeet: '760 sq ft',
    isFurnished: true,
    amenities: ['Elevator', 'Laundry Service'],
    stayType: 'ls',
    isNegotiable: false,
    description:
      'A charming one-bedroom apartment with a cozy atmosphere and modern updates. Great for professionals or couples seeking a comfortable home.',
    owner: 'john.doe@example.com',
  },
  {
    id: 5,
    name: 'Modern Loft',
    title: 'Open-Plan Loft for Contemporary City Living',
    type: 'Apartment',
    image: 'images/apartment-5.jpg',
    rent: 2500,
    location: 'Downtown',
    isShared: true,
    areaInSqFeet: '980 sq ft',
    isFurnished: false,
    amenities: ['Elevator', 'Car Parking', 'Club House'],
    stayType: 'l',
    isNegotiable: true,
    description:
      'A stylish loft apartment with an open floor plan and contemporary design. Perfect for those who appreciate modern living and urban convenience.',
    owner: 'john.doe@example.com',
  },
  {
    id: 6,
    name: 'Sunny Garden Flat',
    title: 'Sunlit Flat with Private Garden Access',
    type: 'Building',
    image: 'images/apartment-6.jpg',
    rent: 1800,
    location: 'Riverside',
    isShared: false,
    areaInSqFeet: '890 sq ft',
    isFurnished: true,
    amenities: ['Private Lawn', 'Garbage Disposal', 'Car Parking'],
    stayType: 's',
    isNegotiable: false,
    description:
      'A bright apartment with garden access, generous windows, and a quiet residential setting.',
    owner: 'john.doe@example.com',
  },
  {
    id: 7,
    name: 'Quiet Corner Apartment',
    title: 'Peaceful Corner Apartment Near Local Shops',
    type: 'Apartment',
    image: 'images/apartment-1.jpg',
    rent: 1350,
    location: 'Oak District',
    isShared: false,
    areaInSqFeet: '680 sq ft',
    isFurnished: false,
    amenities: ['Gated Security', 'Laundry Service'],
    stayType: 'l',
    isNegotiable: true,
    description:
      'A peaceful one-bedroom home near local shops, parks, and convenient public transportation.',
    owner: 'john.doe@example.com',
  },
  {
    id: 8,
    name: 'Riverside Two-Bedroom',
    title: 'Spacious Riverside Home with Natural Light',
    type: 'Building',
    image: 'images/apartment-2.jpg',
    rent: 2200,
    location: 'Riverside',
    isShared: true,
    areaInSqFeet: '1,180 sq ft',
    isFurnished: true,
    amenities: ['Car Parking', 'Visitor Parking', 'Elevator'],
    stayType: 'ls',
    isNegotiable: false,
    description:
      'A spacious two-bedroom apartment with natural light, generous storage, and nearby walking paths.',
    owner: 'john.doe@example.com',
  },
  {
    id: 9,
    name: 'Skyline View Home',
    title: 'Stylish Home with Wide Skyline Views',
    type: 'Apartment',
    image: 'images/apartment-3.jpg',
    rent: 3100,
    location: 'Uptown',
    isShared: false,
    areaInSqFeet: '1,350 sq ft',
    isFurnished: true,
    amenities: ['Gym', 'Elevator', 'Gated Security'],
    stayType: 'l',
    isNegotiable: true,
    description:
      'A stylish home with wide skyline views, updated finishes, and easy access to restaurants and culture.',
    owner: 'john.doe@example.com',
  },
  {
    id: 10,
    name: 'Maple Street Retreat',
    title: 'Welcoming Home on a Tree-Lined Street',
    type: 'Building',
    image: 'images/apartment-4.jpg',
    rent: 1600,
    location: 'Maple Heights',
    isShared: false,
    areaInSqFeet: '820 sq ft',
    isFurnished: false,
    amenities: ['Private Lawn', 'Car Parking'],
    stayType: 's',
    isNegotiable: false,
    description:
      'A comfortable apartment on a tree-lined street with a welcoming layout and modern kitchen.',
    owner: 'john.doe@example.com',
  },
  {
    id: 11,
    name: 'Industrial Design Loft',
    title: 'Characterful Loft with High Ceilings',
    type: 'Building',
    image: 'images/apartment-5.jpg',
    rent: 2700,
    location: 'Warehouse Quarter',
    isShared: true,
    areaInSqFeet: '1,050 sq ft',
    isFurnished: false,
    amenities: ['Elevator', 'Club House', 'Visitor Parking'],
    stayType: 'l',
    isNegotiable: true,
    description:
      'An open loft with high ceilings, exposed details, and plenty of room for work and entertaining.',
    owner: 'john.doe@example.com',
  },
  {
    id: 12,
    name: 'Lakeside Studio',
    title: 'Efficient Lakeside Studio for Relaxed Living',
    type: 'Apartment',
    image: 'images/apartment-6.jpg',
    rent: 1450,
    location: 'Lakeside',
    isShared: false,
    areaInSqFeet: '560 sq ft',
    isFurnished: true,
    amenities: ['Laundry Service', 'Gated Security'],
    stayType: 's',
    isNegotiable: false,
    description:
      'A compact studio close to the water, with an efficient floor plan and a relaxed neighborhood feel.',
    owner: 'john.doe@example.com',
  },
  {
    id: 13,
    name: 'Central Parkside Flat',
    title: 'Comfortable Flat Beside Central Green Space',
    type: 'Apartment',
    image: 'images/apartment-1.jpg',
    rent: 1750,
    location: 'Parkside',
    isShared: false,
    areaInSqFeet: '840 sq ft',
    isFurnished: false,
    amenities: ['Elevator', 'Garbage Disposal', 'Car Parking'],
    stayType: 'ls',
    isNegotiable: true,
    description:
      'A well-kept flat beside green space, offering a practical layout and a short commute downtown.',
    owner: 'john.doe@example.com',
  },
  {
    id: 14,
    name: 'Family-Friendly Residence',
    title: 'Roomy Residence with Family Amenities',
    type: 'Building',
    image: 'images/apartment-2.jpg',
    rent: 2400,
    location: 'Westwood',
    isShared: true,
    areaInSqFeet: '1,280 sq ft',
    isFurnished: true,
    amenities: ['Club House', 'Private Lawn', 'Car Parking'],
    stayType: 'l',
    isNegotiable: false,
    description:
      'A roomy residence with two bedrooms, a flexible living area, and family-friendly community amenities.',
    owner: 'john.doe@example.com',
  },
  {
    id: 15,
    name: 'Executive City Suite',
    title: 'Polished Suite Close to Offices and Transit',
    type: 'Building',
    image: 'images/apartment-3.jpg',
    rent: 3600,
    location: 'Financial District',
    isShared: false,
    areaInSqFeet: '1,460 sq ft',
    isFurnished: true,
    amenities: ['Gym', 'Elevator', 'Power Backup'],
    stayType: 's',
    isNegotiable: true,
    description:
      'A polished city suite with premium appliances and quick access to offices, dining, and transit.',
    owner: 'john.doe@example.com',
  },
  {
    id: 16,
    name: 'Warm Midtown Home',
    title: 'Warm and Welcoming Midtown Home',
    type: 'Apartment',
    image: 'images/apartment-4.jpg',
    rent: 1900,
    location: 'Midtown',
    isShared: false,
    areaInSqFeet: '920 sq ft',
    isFurnished: true,
    amenities: ['Laundry Service', 'Elevator'],
    stayType: 'l',
    isNegotiable: false,
    description:
      'A welcoming apartment with a balanced layout, updated fixtures, and convenient neighborhood services.',
    owner: 'john.doe@example.com',
  },
  {
    id: 17,
    name: 'Creative District Loft',
    title: 'Flexible Loft Near Galleries and Cafes',
    type: 'Building',
    image: 'images/apartment-5.jpg',
    rent: 2300,
    location: 'Arts District',
    isShared: true,
    areaInSqFeet: '1,010 sq ft',
    isFurnished: false,
    amenities: ['Elevator', 'Club House', 'Visitor Parking'],
    stayType: 'ls',
    isNegotiable: true,
    description:
      'A character-filled loft near galleries and cafes, with an open living area and flexible workspace.',
    owner: 'john.doe@example.com',
  },
  {
    id: 18,
    name: 'Sunlit Terrace Apartment',
    title: 'Sunlit Apartment with a Private Terrace',
    type: 'Apartment',
    image: 'images/apartment-6.jpg',
    rent: 2100,
    location: 'Hillcrest',
    isShared: false,
    areaInSqFeet: '1,080 sq ft',
    isFurnished: true,
    amenities: ['Private Lawn', 'Car Parking', 'Gated Security'],
    stayType: 'l',
    isNegotiable: false,
    description:
      'A sunlit apartment with a private terrace, comfortable bedrooms, and calm hilltop surroundings.',
    owner: 'john.doe@example.com',
  },
  {
    id: 19,
    name: 'Compact Commuter Studio',
    title: 'Efficient Studio Steps from Public Transit',
    type: 'Apartment',
    image: 'images/apartment-1.jpg',
    rent: 1100,
    location: 'Transit Village',
    isShared: false,
    areaInSqFeet: '480 sq ft',
    isFurnished: false,
    amenities: ['Elevator', 'Laundry Service'],
    stayType: 's',
    isNegotiable: true,
    description:
      'An efficient studio steps from transit, designed for simple city living and an easy daily commute.',
    owner: 'john.doe@example.com',
  },
  {
    id: 20,
    name: 'Two-Bedroom Courtyard Home',
    title: 'Bright Two-Bedroom Overlooking a Courtyard',
    type: 'Building',
    image: 'images/apartment-2.jpg',
    rent: 2250,
    location: 'Cedar Grove',
    isShared: true,
    areaInSqFeet: '1,240 sq ft',
    isFurnished: true,
    amenities: ['Car Parking', 'Private Lawn', 'Garbage Disposal'],
    stayType: 'ls',
    isNegotiable: false,
    description:
      'A bright two-bedroom home overlooking a shared courtyard with ample closets and comfortable living space.',
    owner: 'john.doe@example.com',
  },
  {
    id: 21,
    name: 'Elevated Urban Penthouse',
    title: 'Elevated Penthouse with Dramatic City Views',
    type: 'Building',
    image: 'images/apartment-3.jpg',
    rent: 4800,
    location: 'Crown Hill',
    isShared: false,
    areaInSqFeet: '2,180 sq ft',
    isFurnished: true,
    amenities: ['Swimming Pool', 'Gym', 'Power Backup', 'Elevator'],
    stayType: 'l',
    isNegotiable: true,
    description:
      'An elevated penthouse with dramatic windows, refined finishes, and expansive views across the city.',
    owner: 'john.doe@example.com',
  },
  {
    id: 22,
    name: 'Brick Row Apartment',
    title: 'Historic Brick Apartment with Modern Comforts',
    type: 'Apartment',
    image: 'images/apartment-4.jpg',
    rent: 1550,
    location: 'Old Town',
    isShared: false,
    areaInSqFeet: '730 sq ft',
    isFurnished: false,
    amenities: ['Gated Security', 'Laundry Service'],
    stayType: 's',
    isNegotiable: false,
    description:
      'A charming apartment in a historic brick building with character, comfort, and modern conveniences.',
    owner: 'john.doe@example.com',
  },
  {
    id: 23,
    name: 'Open Plan City Loft',
    title: 'Versatile Open-Plan Loft in the City',
    type: 'Building',
    image: 'images/apartment-5.jpg',
    rent: 2600,
    location: 'Downtown',
    isShared: true,
    areaInSqFeet: '1,160 sq ft',
    isFurnished: false,
    amenities: ['Elevator', 'Car Parking', 'Club House'],
    stayType: 'l',
    isNegotiable: true,
    description:
      'A versatile open-plan loft near city life, with tall windows and space for both living and working.',
    owner: 'john.doe@example.com',
  },
  {
    id: 24,
    name: 'Meadow View Apartment',
    title: 'Relaxed Apartment with Leafy Meadow Views',
    type: 'Apartment',
    image: 'images/apartment-6.jpg',
    rent: 1700,
    location: 'Meadow Lane',
    isShared: false,
    areaInSqFeet: '860 sq ft',
    isFurnished: true,
    amenities: ['Private Lawn', 'Car Parking'],
    stayType: 'ls',
    isNegotiable: false,
    description:
      'A relaxed apartment with leafy views, a comfortable kitchen, and a peaceful location near walking trails.',
    owner: 'john.doe@example.com',
  },
  {
    id: 25,
    name: 'Neighborhood Studio',
    title: 'Tidy Studio Close to Everyday Essentials',
    type: 'Apartment',
    image: 'images/apartment-1.jpg',
    rent: 1250,
    location: 'Brookfield',
    isShared: false,
    areaInSqFeet: '510 sq ft',
    isFurnished: false,
    amenities: ['Laundry Service', 'Gated Security'],
    stayType: 's',
    isNegotiable: true,
    description:
      'A tidy studio in a friendly neighborhood, close to groceries, cafes, and everyday essentials.',
    owner: 'john.doe@example.com',
  },
  {
    id: 26,
    name: 'Bright Family Flat',
    title: 'Bright Family Flat Near Parks and Schools',
    type: 'Building',
    image: 'images/apartment-2.jpg',
    rent: 2350,
    location: 'Northgate',
    isShared: true,
    areaInSqFeet: '1,300 sq ft',
    isFurnished: true,
    amenities: ['Club House', 'Car Parking', 'Visitor Parking'],
    stayType: 'l',
    isNegotiable: false,
    description:
      'A bright family flat with two bedrooms, a spacious lounge, and excellent access to schools and parks.',
    owner: 'john.doe@example.com',
  },
  {
    id: 27,
    name: 'Harborfront Residence',
    title: 'Refined Harborfront Residence with Open Views',
    type: 'Building',
    image: 'images/apartment-3.jpg',
    rent: 3300,
    location: 'Harborfront',
    isShared: false,
    areaInSqFeet: '1,520 sq ft',
    isFurnished: true,
    amenities: ['Swimming Pool', 'Gym', 'Elevator'],
    stayType: 'ls',
    isNegotiable: true,
    description:
      'A refined residence near the harbor with open views, high-quality finishes, and a lively neighborhood.',
    owner: 'john.doe@example.com',
  },
  {
    id: 28,
    name: 'Classic One-Bedroom',
    title: 'Classic One-Bedroom with a Practical Layout',
    type: 'Apartment',
    image: 'images/apartment-4.jpg',
    rent: 1400,
    location: 'Elmwood',
    isShared: false,
    areaInSqFeet: '710 sq ft',
    isFurnished: false,
    amenities: ['Garbage Disposal', 'Laundry Service'],
    stayType: 'l',
    isNegotiable: false,
    description:
      'A classic one-bedroom apartment with a practical layout, warm details, and excellent local amenities.',
    owner: 'john.doe@example.com',
  },
  {
    id: 29,
    name: 'Designer Loft Residence',
    title: 'Designer Loft with Striking Finishes',
    type: 'Building',
    image: 'images/apartment-5.jpg',
    rent: 2950,
    location: 'Design Quarter',
    isShared: true,
    areaInSqFeet: '1,240 sq ft',
    isFurnished: true,
    amenities: ['Elevator', 'Gym', 'Power Backup'],
    stayType: 'l',
    isNegotiable: true,
    description:
      'A designer loft with striking finishes, generous light, and a central address for urban explorers.',
    owner: 'john.doe@example.com',
  },
  {
    id: 30,
    name: 'Quiet Courtyard Studio',
    title: 'Private Studio Facing a Landscaped Courtyard',
    type: 'Apartment',
    image: 'images/apartment-6.jpg',
    rent: 1300,
    location: 'Garden Quarter',
    isShared: false,
    areaInSqFeet: '540 sq ft',
    isFurnished: false,
    amenities: ['Private Lawn', 'Gated Security'],
    stayType: 's',
    isNegotiable: false,
    description:
      'A quiet studio facing a landscaped courtyard, offering privacy and a simple, efficient living space.',
    owner: 'john.doe@example.com',
  },
  {
    id: 31,
    name: 'Downtown Corner Flat',
    title: 'Light-Filled Corner Flat in Downtown',
    type: 'Apartment',
    image: 'images/apartment-1.jpg',
    rent: 1850,
    location: 'Downtown',
    isShared: false,
    areaInSqFeet: '900 sq ft',
    isFurnished: true,
    amenities: ['Elevator', 'Car Parking', 'Gated Security'],
    stayType: 'l',
    isNegotiable: false,
    description:
      'A corner flat with excellent daylight, a flexible living area, and the best of downtown nearby.',
    owner: 'john.doe@example.com',
  },
  {
    id: 32,
    name: 'Spacious Park View',
    title: 'Spacious Home Overlooking the Park',
    type: 'Building',
    image: 'images/apartment-2.jpg',
    rent: 2500,
    location: 'Parkside',
    isShared: true,
    areaInSqFeet: '1,380 sq ft',
    isFurnished: false,
    amenities: ['Private Lawn', 'Club House', 'Visitor Parking'],
    stayType: 'ls',
    isNegotiable: true,
    description:
      'A spacious apartment overlooking the park with generous bedrooms, storage, and a comfortable kitchen.',
    owner: 'john.doe@example.com',
  },
  {
    id: 33,
    name: 'Luxury River Residence',
    title: 'Elegant Riverfront Residence with Premium Services',
    type: 'Building',
    image: 'images/apartment-3.jpg',
    rent: 4100,
    location: 'Riverside',
    isShared: false,
    areaInSqFeet: '1,760 sq ft',
    isFurnished: true,
    amenities: ['Swimming Pool', 'Gym', 'Elevator', 'Power Backup'],
    stayType: 'l',
    isNegotiable: true,
    description:
      'A luxurious riverfront residence with elegant interiors, wide windows, and premium building services.',
    owner: 'john.doe@example.com',
  },
  {
    id: 34,
    name: 'Cozy Transit-Side Home',
    title: 'Comfortable Home Close to Major Transit Links',
    type: 'Apartment',
    image: 'images/apartment-4.jpg',
    rent: 1500,
    location: 'Transit Village',
    isShared: false,
    areaInSqFeet: '780 sq ft',
    isFurnished: false,
    amenities: ['Laundry Service', 'Car Parking'],
    stayType: 's',
    isNegotiable: false,
    description:
      'A cozy home close to major transit links, with a comfortable bedroom and a welcoming living room.',
    owner: 'john.doe@example.com',
  },
  {
    id: 35,
    name: 'Modern Warehouse Loft',
    title: 'Modern Loft with Tall Ceilings and Open Space',
    type: 'Building',
    image: 'images/apartment-5.jpg',
    rent: 2800,
    location: 'Warehouse Quarter',
    isShared: true,
    areaInSqFeet: '1,280 sq ft',
    isFurnished: true,
    amenities: ['Elevator', 'Club House', 'Car Parking'],
    stayType: 'l',
    isNegotiable: true,
    description:
      'A modern warehouse loft with open space, tall ceilings, and a lively mix of dining and creative venues.',
    owner: 'john.doe@example.com',
  },
  {
    id: 36,
    name: 'Hillside Garden Home',
    title: 'Peaceful Hillside Home Surrounded by Greenery',
    type: 'Apartment',
    image: 'images/apartment-6.jpg',
    rent: 2050,
    location: 'Hillcrest',
    isShared: false,
    areaInSqFeet: '1,040 sq ft',
    isFurnished: false,
    amenities: ['Private Lawn', 'Garbage Disposal', 'Car Parking'],
    stayType: 'ls',
    isNegotiable: false,
    description:
      'A peaceful hillside home surrounded by greenery, with a bright interior and room to settle in.',
    owner: 'john.doe@example.com',
  },
  {
    id: 37,
    name: 'Efficient City Studio',
    title: 'Efficient Studio for City Professionals',
    type: 'Apartment',
    image: 'images/apartment-1.jpg',
    rent: 1150,
    location: 'Central Station',
    isShared: false,
    areaInSqFeet: '500 sq ft',
    isFurnished: true,
    amenities: ['Elevator', 'Laundry Service'],
    stayType: 's',
    isNegotiable: true,
    description:
      'An efficient studio for city professionals, located near transit, markets, and neighborhood restaurants.',
    owner: 'john.doe@example.com',
  },
  {
    id: 38,
    name: 'Cedar Grove Two-Bedroom',
    title: 'Comfortable Two-Bedroom with Tree-Lined Views',
    type: 'Building',
    image: 'images/apartment-2.jpg',
    rent: 2150,
    location: 'Cedar Grove',
    isShared: true,
    areaInSqFeet: '1,210 sq ft',
    isFurnished: false,
    amenities: ['Car Parking', 'Visitor Parking', 'Gated Security'],
    stayType: 'l',
    isNegotiable: false,
    description:
      'A comfortable two-bedroom apartment with tree-lined views, practical storage, and a welcoming layout.',
    owner: 'john.doe@example.com',
  },
  {
    id: 39,
    name: 'Uptown Sunset Suite',
    title: 'Elegant Uptown Suite with Sunset Light',
    type: 'Building',
    image: 'images/apartment-3.jpg',
    rent: 3500,
    location: 'Uptown',
    isShared: false,
    areaInSqFeet: '1,420 sq ft',
    isFurnished: true,
    amenities: ['Gym', 'Elevator', 'Swimming Pool'],
    stayType: 'ls',
    isNegotiable: true,
    description:
      'An elegant uptown suite with beautiful sunset light, modern amenities, and a polished atmosphere.',
    owner: 'john.doe@example.com',
  },
  {
    id: 40,
    name: 'Maple Heights Flat',
    title: 'Comfortable Flat in a Calm Neighborhood',
    type: 'Apartment',
    image: 'images/apartment-4.jpg',
    rent: 1650,
    location: 'Maple Heights',
    isShared: false,
    areaInSqFeet: '810 sq ft',
    isFurnished: false,
    amenities: ['Garbage Disposal', 'Laundry Service'],
    stayType: 'l',
    isNegotiable: false,
    description:
      'A comfortable flat in a calm neighborhood, with updated interiors and quick access to local shops.',
    owner: 'john.doe@example.com',
  },
  {
    id: 41,
    name: 'Arts District Studio Loft',
    title: 'Creative Studio Loft Near Independent Shops',
    type: 'Building',
    image: 'images/apartment-5.jpg',
    rent: 2450,
    location: 'Arts District',
    isShared: true,
    areaInSqFeet: '1,000 sq ft',
    isFurnished: true,
    amenities: ['Elevator', 'Club House', 'Visitor Parking'],
    stayType: 'l',
    isNegotiable: true,
    description:
      'A creative studio loft surrounded by galleries, cafes, and independent shops in a vibrant district.',
    owner: 'john.doe@example.com',
  },
  {
    id: 42,
    name: 'Lakeside Family Apartment',
    title: 'Roomy Family Apartment Near the Lake',
    type: 'Building',
    image: 'images/apartment-6.jpg',
    rent: 2300,
    location: 'Lakeside',
    isShared: false,
    areaInSqFeet: '1,260 sq ft',
    isFurnished: false,
    amenities: ['Car Parking', 'Private Lawn', 'Garbage Disposal'],
    stayType: 'ls',
    isNegotiable: false,
    description:
      'A roomy family apartment near the lake, with a relaxed setting and plenty of everyday convenience.',
    owner: 'john.doe@example.com',
  },
  {
    id: 43,
    name: 'Oak District One-Bedroom',
    title: 'Thoughtful One-Bedroom on a Quiet Street',
    type: 'Apartment',
    image: 'images/apartment-1.jpg',
    rent: 1450,
    location: 'Oak District',
    isShared: false,
    areaInSqFeet: '740 sq ft',
    isFurnished: true,
    amenities: ['Gated Security', 'Laundry Service'],
    stayType: 's',
    isNegotiable: true,
    description:
      'A warm one-bedroom apartment with thoughtful storage, comfortable finishes, and a quiet street address.',
    owner: 'john.doe@example.com',
  },
  {
    id: 44,
    name: 'Northgate Family Home',
    title: 'Spacious Family Home with Bright Rooms',
    type: 'Building',
    image: 'images/apartment-2.jpg',
    rent: 2650,
    location: 'Northgate',
    isShared: true,
    areaInSqFeet: '1,460 sq ft',
    isFurnished: true,
    amenities: ['Club House', 'Car Parking', 'Private Lawn'],
    stayType: 'l',
    isNegotiable: false,
    description:
      'A spacious family home with bright rooms, a flexible dining area, and easy access to green space.',
    owner: 'john.doe@example.com',
  },
  {
    id: 45,
    name: 'Harbor View Penthouse',
    title: 'Striking Harbor Penthouse for Entertaining',
    type: 'Building',
    image: 'images/apartment-3.jpg',
    rent: 5200,
    location: 'Harborfront',
    isShared: false,
    areaInSqFeet: '2,500 sq ft',
    isFurnished: true,
    amenities: ['Swimming Pool', 'Gym', 'Power Backup', 'Elevator'],
    stayType: 'ls',
    isNegotiable: true,
    description:
      'A striking penthouse with harbor views, premium finishes, and an impressive setting for entertaining.',
    owner: 'john.doe@example.com',
  },
  {
    id: 46,
    name: 'Old Town Character Flat',
    title: 'Character Flat Blending History and Comfort',
    type: 'Apartment',
    image: 'images/apartment-4.jpg',
    rent: 1750,
    location: 'Old Town',
    isShared: false,
    areaInSqFeet: '880 sq ft',
    isFurnished: false,
    amenities: ['Laundry Service', 'Garbage Disposal'],
    stayType: 'l',
    isNegotiable: false,
    description:
      'A character flat blending historic details with modern comfort in the heart of the old town.',
    owner: 'john.doe@example.com',
  },
  {
    id: 47,
    name: 'Central Creative Loft',
    title: 'Flexible Creative Loft with City Connections',
    type: 'Building',
    image: 'images/apartment-5.jpg',
    rent: 2850,
    location: 'Central Station',
    isShared: true,
    areaInSqFeet: '1,180 sq ft',
    isFurnished: true,
    amenities: ['Elevator', 'Car Parking', 'Gated Security'],
    stayType: 'l',
    isNegotiable: true,
    description:
      'A flexible creative loft with an open plan, strong natural light, and excellent city connections.',
    owner: 'john.doe@example.com',
  },
  {
    id: 48,
    name: 'Meadow Lane Retreat',
    title: 'Restful Apartment Near Open Meadows',
    type: 'Apartment',
    image: 'images/apartment-6.jpg',
    rent: 1550,
    location: 'Meadow Lane',
    isShared: false,
    areaInSqFeet: '790 sq ft',
    isFurnished: false,
    amenities: ['Private Lawn', 'Car Parking'],
    stayType: 's',
    isNegotiable: false,
    description:
      'A restful apartment near open meadows, with a comfortable interior and a slower neighborhood rhythm.',
    owner: 'john.doe@example.com',
  },
  {
    id: 49,
    name: 'Brookfield Modern Home',
    title: 'Modern Home in a Welcoming Neighborhood',
    type: 'Building',
    image: 'images/apartment-1.jpg',
    rent: 1950,
    location: 'Brookfield',
    isShared: true,
    areaInSqFeet: '970 sq ft',
    isFurnished: true,
    amenities: ['Gated Security', 'Visitor Parking', 'Laundry Service'],
    stayType: 'ls',
    isNegotiable: true,
    description:
      'A modern home in a welcoming neighborhood, with clean finishes and convenient access to daily essentials.',
    owner: 'john.doe@example.com',
  },
  {
    id: 50,
    name: 'Westwood Spacious Flat',
    title: 'Spacious Flat with Abundant Natural Light',
    type: 'Apartment',
    image: 'images/apartment-2.jpg',
    rent: 2550,
    location: 'Westwood',
    isShared: false,
    areaInSqFeet: '1,340 sq ft',
    isFurnished: false,
    amenities: ['Car Parking', 'Elevator', 'Club House'],
    stayType: 'l',
    isNegotiable: false,
    description:
      'A spacious flat with a flexible layout, abundant light, and a comfortable residential setting.',
    owner: 'john.doe@example.com',
  },
];
